command_timeout = 1000

"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
${custom.giturl}\
$git_branch\
$git_state\
$git_status\
$character\
"""
add_newline = false
palette = 'dracula'

[directory]
style = "bold fg:green"
format = "[$path ]($style)"
#style = 'bold fg:dark_blue'
#format = '[$path ]($style)'
truncation_length = 1
#truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[custom.giturl]
# disabled = true
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
format = "at $output"

[git_branch]
symbol = "[](black) "
# format =  ' [$symbol$branch(:$remote_branch)]($style)[]'
style = "bold fg:pink bg:black"
format =  '  on [$symbol$branch]($style)[](black)'

[git_status]
style = 'bold fg:red'
format = ' [($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
format = '[ $symbol( $version) ]($style)'

[c]
symbol = " "
format = '[[ $symbol( $version) ]]($style)'

[rust]
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[golang]
symbol = ""
format = '[ $symbol( $version) ]($style)'
detect_files = ["go.mod"]

[php]
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[java]
symbol = " "
format = '[[ $symbol( $version) ]]($style)'

[kotlin]
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[haskell]
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[python]
symbol = ""
format = '[[ $symbol( $version) ]]($style)'


[docker_context]
symbol = ""
format = '[ $symbol( $context) ]($style)'

[character]
format = '$symbol '
success_symbol = '[](bold fg:green)'
error_symbol = '[✘](bold fg:red)'
vimcmd_symbol = '[V](bold fg:green)'

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

#[palettes.onedark]
#dark_blue='#61afef'
#blue='#56b6c2'
#red='#e06c75'
#green='#98c379'
#purple='#e67aff'
#cyan='#56b6c2'
#orange='#be5046'
#yellow='#e5c07b'
#gray='#828997'
#white ='#abb2bf'
#black='#2c323c'

#[palettes.catppuccin_mocha]
#dark_blue='#61afef'
#rosewater = "#f5e0dc"
#flamingo = "#f2cdcd"
#pink = "#f5c2e7"
#mauve = "#cba6f7"
#red='#e06c75'
#maroon = "#eba0ac"
#peach = "#fab387"
#yellow = "#f9e2af"
#green='#98c379'
#teal = "#94e2d5"
#sky = "#89dceb"
#sapphire = "#74c7ec"
#blue = "#56b6c2"
#lavender = "#b4befe"
#text = "#cdd6f4"
#subtext1 = "#bac2de"
#subtext0 = "#a6adc8"
#overlay2 = "#9399b2"
#overlay1 = "#7f849c"
#overlay0 = "#6c7086"
#surface2 = "#585b70"
#surface1 = "#45475a"
#surface0 = "#313244"
#base = "#1e1e2e"
#mantle = "#181825"
#crust = "#11111b"
